// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ActivityAvgLevel.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace StellaSoraParser.Proto {

  /// <summary>Holder for reflection information generated from ActivityAvgLevel.proto</summary>
  public static partial class ActivityAvgLevelReflection {

    #region Descriptor
    /// <summary>File descriptor for ActivityAvgLevel.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActivityAvgLevelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZBY3Rpdml0eUF2Z0xldmVsLnByb3RvEhZTdGVsbGFTb3JhUGFyc2VyLlBy",
            "b3RvIu0BChBBY3Rpdml0eUF2Z0xldmVsEgoKAklkGAEgASgFEhIKCkFjdGl2",
            "aXR5SWQYAiABKAUSFQoNUGVyc29uYWxpdHlJZBgDIAEoBRIPCgdEYXlPcGVu",
            "GAQgASgFEg0KBUluZGV4GAUgASgJEgwKBE5hbWUYBiABKAkSDwoHSWNvblJl",
            "cxgHIAEoCRIMCgRUeXBlGAggASgFEhIKClByZUxldmVsSWQYCSABKAUSDwoH",
            "U3RvcnlJZBgKIAEoCRIMCgREZXNjGAsgASgJEiIKGkZpcnN0Q29tcGxldGVS",
            "ZXdhcmRQcmV2aWV3GAwgASgJIlAKFnRhYmxlX0FjdGl2aXR5QXZnTGV2ZWwS",
            "NgoETGlzdBgBIAMoCzIoLlN0ZWxsYVNvcmFQYXJzZXIuUHJvdG8uQWN0aXZp",
            "dHlBdmdMZXZlbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::StellaSoraParser.Proto.ActivityAvgLevel), global::StellaSoraParser.Proto.ActivityAvgLevel.Parser, new[]{ "Id", "ActivityId", "PersonalityId", "DayOpen", "Index", "Name", "IconRes", "Type", "PreLevelId", "StoryId", "Desc", "FirstCompleteRewardPreview" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StellaSoraParser.Proto.table_ActivityAvgLevel), global::StellaSoraParser.Proto.table_ActivityAvgLevel.Parser, new[]{ "List" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActivityAvgLevel : pb::IMessage<ActivityAvgLevel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActivityAvgLevel> _parser = new pb::MessageParser<ActivityAvgLevel>(() => new ActivityAvgLevel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActivityAvgLevel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StellaSoraParser.Proto.ActivityAvgLevelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityAvgLevel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityAvgLevel(ActivityAvgLevel other) : this() {
      id_ = other.id_;
      activityId_ = other.activityId_;
      personalityId_ = other.personalityId_;
      dayOpen_ = other.dayOpen_;
      index_ = other.index_;
      name_ = other.name_;
      iconRes_ = other.iconRes_;
      type_ = other.type_;
      preLevelId_ = other.preLevelId_;
      storyId_ = other.storyId_;
      desc_ = other.desc_;
      firstCompleteRewardPreview_ = other.firstCompleteRewardPreview_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActivityAvgLevel Clone() {
      return new ActivityAvgLevel(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "ActivityId" field.</summary>
    public const int ActivityIdFieldNumber = 2;
    private int activityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ActivityId {
      get { return activityId_; }
      set {
        activityId_ = value;
      }
    }

    /// <summary>Field number for the "PersonalityId" field.</summary>
    public const int PersonalityIdFieldNumber = 3;
    private int personalityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PersonalityId {
      get { return personalityId_; }
      set {
        personalityId_ = value;
      }
    }

    /// <summary>Field number for the "DayOpen" field.</summary>
    public const int DayOpenFieldNumber = 4;
    private int dayOpen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DayOpen {
      get { return dayOpen_; }
      set {
        dayOpen_ = value;
      }
    }

    /// <summary>Field number for the "Index" field.</summary>
    public const int IndexFieldNumber = 5;
    private string index_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Index {
      get { return index_; }
      set {
        index_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 6;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "IconRes" field.</summary>
    public const int IconResFieldNumber = 7;
    private string iconRes_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IconRes {
      get { return iconRes_; }
      set {
        iconRes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 8;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "PreLevelId" field.</summary>
    public const int PreLevelIdFieldNumber = 9;
    private int preLevelId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PreLevelId {
      get { return preLevelId_; }
      set {
        preLevelId_ = value;
      }
    }

    /// <summary>Field number for the "StoryId" field.</summary>
    public const int StoryIdFieldNumber = 10;
    private string storyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StoryId {
      get { return storyId_; }
      set {
        storyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Desc" field.</summary>
    public const int DescFieldNumber = 11;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FirstCompleteRewardPreview" field.</summary>
    public const int FirstCompleteRewardPreviewFieldNumber = 12;
    private string firstCompleteRewardPreview_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirstCompleteRewardPreview {
      get { return firstCompleteRewardPreview_; }
      set {
        firstCompleteRewardPreview_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActivityAvgLevel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActivityAvgLevel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ActivityId != other.ActivityId) return false;
      if (PersonalityId != other.PersonalityId) return false;
      if (DayOpen != other.DayOpen) return false;
      if (Index != other.Index) return false;
      if (Name != other.Name) return false;
      if (IconRes != other.IconRes) return false;
      if (Type != other.Type) return false;
      if (PreLevelId != other.PreLevelId) return false;
      if (StoryId != other.StoryId) return false;
      if (Desc != other.Desc) return false;
      if (FirstCompleteRewardPreview != other.FirstCompleteRewardPreview) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (ActivityId != 0) hash ^= ActivityId.GetHashCode();
      if (PersonalityId != 0) hash ^= PersonalityId.GetHashCode();
      if (DayOpen != 0) hash ^= DayOpen.GetHashCode();
      if (Index.Length != 0) hash ^= Index.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (IconRes.Length != 0) hash ^= IconRes.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (PreLevelId != 0) hash ^= PreLevelId.GetHashCode();
      if (StoryId.Length != 0) hash ^= StoryId.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (FirstCompleteRewardPreview.Length != 0) hash ^= FirstCompleteRewardPreview.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (ActivityId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ActivityId);
      }
      if (PersonalityId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PersonalityId);
      }
      if (DayOpen != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(DayOpen);
      }
      if (Index.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Index);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Name);
      }
      if (IconRes.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(IconRes);
      }
      if (Type != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Type);
      }
      if (PreLevelId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(PreLevelId);
      }
      if (StoryId.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(StoryId);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Desc);
      }
      if (FirstCompleteRewardPreview.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(FirstCompleteRewardPreview);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (ActivityId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ActivityId);
      }
      if (PersonalityId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PersonalityId);
      }
      if (DayOpen != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(DayOpen);
      }
      if (Index.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Index);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Name);
      }
      if (IconRes.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(IconRes);
      }
      if (Type != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Type);
      }
      if (PreLevelId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(PreLevelId);
      }
      if (StoryId.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(StoryId);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Desc);
      }
      if (FirstCompleteRewardPreview.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(FirstCompleteRewardPreview);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (ActivityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActivityId);
      }
      if (PersonalityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PersonalityId);
      }
      if (DayOpen != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DayOpen);
      }
      if (Index.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Index);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (IconRes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IconRes);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (PreLevelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PreLevelId);
      }
      if (StoryId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StoryId);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (FirstCompleteRewardPreview.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstCompleteRewardPreview);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActivityAvgLevel other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.ActivityId != 0) {
        ActivityId = other.ActivityId;
      }
      if (other.PersonalityId != 0) {
        PersonalityId = other.PersonalityId;
      }
      if (other.DayOpen != 0) {
        DayOpen = other.DayOpen;
      }
      if (other.Index.Length != 0) {
        Index = other.Index;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.IconRes.Length != 0) {
        IconRes = other.IconRes;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.PreLevelId != 0) {
        PreLevelId = other.PreLevelId;
      }
      if (other.StoryId.Length != 0) {
        StoryId = other.StoryId;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      if (other.FirstCompleteRewardPreview.Length != 0) {
        FirstCompleteRewardPreview = other.FirstCompleteRewardPreview;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            ActivityId = input.ReadInt32();
            break;
          }
          case 24: {
            PersonalityId = input.ReadInt32();
            break;
          }
          case 32: {
            DayOpen = input.ReadInt32();
            break;
          }
          case 42: {
            Index = input.ReadString();
            break;
          }
          case 50: {
            Name = input.ReadString();
            break;
          }
          case 58: {
            IconRes = input.ReadString();
            break;
          }
          case 64: {
            Type = input.ReadInt32();
            break;
          }
          case 72: {
            PreLevelId = input.ReadInt32();
            break;
          }
          case 82: {
            StoryId = input.ReadString();
            break;
          }
          case 90: {
            Desc = input.ReadString();
            break;
          }
          case 98: {
            FirstCompleteRewardPreview = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            ActivityId = input.ReadInt32();
            break;
          }
          case 24: {
            PersonalityId = input.ReadInt32();
            break;
          }
          case 32: {
            DayOpen = input.ReadInt32();
            break;
          }
          case 42: {
            Index = input.ReadString();
            break;
          }
          case 50: {
            Name = input.ReadString();
            break;
          }
          case 58: {
            IconRes = input.ReadString();
            break;
          }
          case 64: {
            Type = input.ReadInt32();
            break;
          }
          case 72: {
            PreLevelId = input.ReadInt32();
            break;
          }
          case 82: {
            StoryId = input.ReadString();
            break;
          }
          case 90: {
            Desc = input.ReadString();
            break;
          }
          case 98: {
            FirstCompleteRewardPreview = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class table_ActivityAvgLevel : pb::IMessage<table_ActivityAvgLevel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<table_ActivityAvgLevel> _parser = new pb::MessageParser<table_ActivityAvgLevel>(() => new table_ActivityAvgLevel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<table_ActivityAvgLevel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StellaSoraParser.Proto.ActivityAvgLevelReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public table_ActivityAvgLevel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public table_ActivityAvgLevel(table_ActivityAvgLevel other) : this() {
      list_ = other.list_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public table_ActivityAvgLevel Clone() {
      return new table_ActivityAvgLevel(this);
    }

    /// <summary>Field number for the "List" field.</summary>
    public const int ListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::StellaSoraParser.Proto.ActivityAvgLevel> _repeated_list_codec
        = pb::FieldCodec.ForMessage(10, global::StellaSoraParser.Proto.ActivityAvgLevel.Parser);
    private readonly pbc::RepeatedField<global::StellaSoraParser.Proto.ActivityAvgLevel> list_ = new pbc::RepeatedField<global::StellaSoraParser.Proto.ActivityAvgLevel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::StellaSoraParser.Proto.ActivityAvgLevel> List {
      get { return list_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as table_ActivityAvgLevel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(table_ActivityAvgLevel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!list_.Equals(other.list_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= list_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      list_.WriteTo(output, _repeated_list_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      list_.WriteTo(ref output, _repeated_list_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += list_.CalculateSize(_repeated_list_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(table_ActivityAvgLevel other) {
      if (other == null) {
        return;
      }
      list_.Add(other.list_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            list_.AddEntriesFrom(input, _repeated_list_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            list_.AddEntriesFrom(ref input, _repeated_list_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
